/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.natica.expense;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridLayout;
import org.natica.expense.exceptions.ExpenseExcelFormatException;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Anil
 */
public class ExpenseForm extends javax.swing.JFrame {
    private List<Expense> expenses;
    /**
     * Creates new form ExpenseForm
     */
    public ExpenseForm() {
        fillExpenseTypeMap();
        initComponents();
    }
    
    private void fillExpenseTypeMap() {
        for (String[] EXPENSETYPES : ExpenseConstants.EXPENSETYPES) {
            ExpenseConstants.expenseTypeMap.put(EXPENSETYPES[0], Integer.parseInt(EXPENSETYPES[1]));
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.getViewport().setBackground(Color.white);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        jMenu1.setText("Dosya");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/natica/expense/images/1433559149_open-file.png"))); // NOI18N
        jMenuItem1.setText("Excel Aç");
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/natica/expense/images/1433559346_vector_65_04.png"))); // NOI18N
        jMenuItem2.setText("Yükle");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String fileExtension = selectedFile.getName().substring(selectedFile.getName().indexOf(".")+1);
            if ("xls".equals(fileExtension) || "xlsx".equals(fileExtension)) {
                ExpenseUtility xp = new ExpenseUtility();
                try {
                    ExpenseBuilder eb = new ExpenseBuilder();
                    DefaultTableModel model = new DefaultTableModel() {
                        @Override
                        public boolean isCellEditable(int row, int column) {
                            //return column != 0 && column != 5;
                            return false;
                        }                        
                    };
                    JTable table = new JTable(model);
                    eb.generateHeaders(model);
                    table.getColumnModel().getColumn(0).setPreferredWidth(70);
                    table.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(eb.generateProjectComboBox()));
                    table.getColumnModel().getColumn(1).setPreferredWidth(150);
                    table.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(eb.generateExpenseTypeComboBox()));
                    table.getColumnModel().getColumn(2).setPreferredWidth(110);
                    table.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(eb.generatePaymentMethodComboBox()));
                    table.getColumnModel().getColumn(3).setPreferredWidth(120);
                    table.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(eb.generateCurrencyComboBox()));
                    table.getColumnModel().getColumn(4).setPreferredWidth(70);
                    table.getColumnModel().getColumn(5).setPreferredWidth(50);
                    table.getColumnModel().getColumn(6).setPreferredWidth(550);
                    DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
                    rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
                    table.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
                    expenses = xp.parseExcel(selectedFile);
                    xp.generateDescription(expenses);
                    eb.populateTable(model, expenses);

                    jScrollPane1.setViewportView(table);
                } catch (IOException ex) {
                    Logger.getLogger(ExpenseForm.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Dosya Okuma Hatası!", JOptionPane.ERROR_MESSAGE);
                } catch (ExpenseExcelFormatException ex) {
                    Logger.getLogger(ExpenseForm.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Excel Format Hatası!", JOptionPane.ERROR_MESSAGE);
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Yalnızca XLS ve XLSX uzantılı dosyalar kullanılabilir.", "Hatalı Dosya Türü!", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        boolean hasError = false;
        JTextField username = new JTextField();
        JPasswordField  password = new JPasswordField();
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Support Kullanıcı Adı"));
        panel.add(username);
        panel.add(new JLabel("Support Parola"));
        panel.add(password);
        int result = JOptionPane.showConfirmDialog(null, panel, "Onay", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);        
        if (result == JOptionPane.OK_OPTION) {
            ExpenseImport ei = new ExpenseImport(ExpenseConstants.BASEURL);
            char[] passwordArray = password.getPassword();
            String passwordStr = String.valueOf(passwordArray);
            System.out.println(passwordStr);
            if (username.getText() == null || "".equals(username.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Kullanıcı Adı Zorunludur", "Hatalı Giriş!", JOptionPane.ERROR_MESSAGE);                
                hasError = true;
            }
            
            if (passwordArray.length == 0) {
                JOptionPane.showMessageDialog(null, "Parola Zorunludur", "Hatalı Giriş!", JOptionPane.ERROR_MESSAGE);                
                hasError = true;                
            }
            
            if (expenses != null) {
                if (expenses.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Excel yüklenmemiştir.", "Hatalı Giriş!", JOptionPane.ERROR_MESSAGE);                
                    hasError = true;                
                }
            }
            else  {
                JOptionPane.showMessageDialog(null, "Excel yüklenmemiştir.", "Hatalı Giriş!", JOptionPane.ERROR_MESSAGE);                
                hasError = true;                       
            }
            
            if (!hasError)
                ei.importExpenes(expenses, username.getText(), passwordStr);
        }        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpenseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpenseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpenseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpenseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ExpenseForm().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
